name: CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: [ self-hosted, Windows]

    steps:
      - uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo "Hello, world! ${{ vars.VARIAVEL_DEMO }}"

      - name: Run a multi-line script
        run: |
          echo "Add other actions to build,"
          echo "test, and deploy your project."

  deploy-dev:
    needs: build
    uses: BrunoGatti23/pipeline_templetes/.github/workflows/demo-deploy.yml@main
    with:
      variavel-demo: "Demo Dev"
